services:   
  hamba:
    container_name: hamba
    image: pytorch/pytorch:2.1.2-cuda11.8-cudnn8-devel
    volumes:
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
      - ~/workspace/:/workspace
    
    runtime: nvidia
    restart: unless-stopped

    environment:
      PYTHONIOENCODING: utf-8
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all

    stdin_open: true
    tty: true
    privileged: true